name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dsoadmin/caepe-webshop-demo:1.0

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          #--Login
          CAEPE_CLIENTID=${{ vars.CAEPE_CLIENTID }} CAEPE_CLIENTSECRET=${{ secrets.CAEPE_CLIENTSECRET }} caepe-cli/caepe-cli-linux-amd64 login --organization ${{ vars.ORG }}

          #-- Create Deployment
          ./caepe-cli/caepe-cli-linux-amd64 deployment rollout -d ${{ vars.DEPNAME }} --hostname ${{ vars.HOST1 }} --organization ${{ vars.ORG }} --scheme https --debug
          # Check for result
          for n in {1..10}
          do
            sleep 20
            #Get deployment status
            OUTPUT=`./caepe-cli/caepe-cli-linux-amd64 deployment list --hostname ${{ vars.HOST1 }} --organization ${{ vars.ORG }} --raw-output`
            #Extract the result of the deployment
            echo "$OUTPUT" | jq '.[] | select(.name == "${{ vars.DEPNAME }}")'
            RESULT=$(echo "$OUTPUT" | jq '.[] | select(.name == "${{ vars.DEPNAME }}") | .status' | tr -d '"')
            #Check the result of the deployment
            if [ $RESULT == "success" ]
            then
              break
            fi
          done
          if [ $RESULT == "success" ]
          then
            (exit 0)
          else
            (exit 1)
          fi

      #- name: Run Bash script
        #run: |
          #--Login
          #CAEPE_CLIENTID=${{ vars.CAEPE_CLIENTID }} CAEPE_CLIENTSECRET=${{ secrets.CAEPE_CLIENTSECRET }} caepe-cli/caepe-cli-linux-amd64 login --organization ${{ vars.ORG }}

          #-- Create Deployment
          #./caepe-cli/caepe-cli-linux-amd64 deployment rollout -d ${{ vars.DEPNAME }} --hostname ${{ vars.HOST2 }} --organization ${{ vars.ORG }} --scheme https --debug
