apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: dsoadmin/caepe-webshop-demo:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: PriorityLevelConfiguration
metadata:
  name: nginx-api-priority
spec:
  type: Limited
  limited:
    nominalConcurrencyShares: 30 
    limitResponse:
      type: Queue
      queuing:
        queues: 64
        handSize: 6
        queueLengthLimit: 50
---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: nginx-api-schema
spec:
  priorityLevelConfiguration:
    name: nginx-api-priority
  matchingPrecedence: 800
  distinguisherMethod:
    type: ByUser
  rules:
  - resourceRules:
    - verbs: ["get", "list", "watch"]
      apiGroups: ["apps"]
      resources: ["deployments"]
      namespaces: ["default"]
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: default
        namespace: default
